name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Prettier checks
        run: npx prettier . --check

      - name: Run Vitest
        run: pnpm run test

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm run build
